baseURL = "https://shiloh.johnhumphries.dev/"
languageCode = "en-us"
title = "Shiloh"
theme = "shiloh"

enableRobotsTXT = true

[pagination]
  pagerSize = 6

[outputs]
  home = ["HTML", "RSS", "JSON"]

[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[services]
  [services.x]
    disableInlineCSS = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.152.0"

[taxonomies]
  tag = "tags"
  category = "categories"
